### ISSUE TITLE
problem of the get_normals() method

### ISSUE THREAD

**Issue by jiahaoli95** [nerfstudio-project/nerfstudio#1083]
Hi,

In the `get_normals` method in the `Field` class (https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/fields/base_field.py#L77), it uses `backward` with `retain_graph=True`. Wouldn't it have the following two problems?
1. Since `create_graph` is not `True`, the computation of normals will not be differentiable.
2. Calling `backward` might mess up the `grad` information of some other leaf nodes.

I think use `torch.autograd.grad` with `create_graph=True` can solve the problem.
Please correct me if I understand it in the wrong way.

Thank you!

**Comment by terrancewang** [comment]
Hi, thanks for your comment! 

I agree, I think using autograd.grad instead of backwards might cause less issues with the grad information. 

I think setting create_graph as false is OK here because we don't need the computation of the normals to be differentiable. We mainly use these computed normals to train the normal prediction network, so I don't think it's necessary for create_graph to be true because we won't be doing further calculations on the normals. 

I made a PR with the above changes, let me know if this answers your question! 
https://github.com/nerfstudio-project/nerfstudio/pull/1108

**Comment by jiahaoli95** [comment]
Awesome. Thanks!
