### ISSUE TITLE
AttributeError: 'SemanticDataManager' object has no attribute 'train_dataparser_outputs'

### ISSUE THREAD

**Issue by yimingzhou1** [nerfstudio-project/nerfstudio#1118]
**Describe the bug**
When I try to run `semantic-nerfw` on the `friends` dataset by following the instructions on the official document. The training doesn't proceed and it gives me the `AttributeError` shown in the title

**To Reproduce**
1. download the `friends` dataset
2. run `ns-download-data friends`
3. run `ns-train semantic-nerfw`

**Traceback**
```
Traceback (most recent call last):
  File "/home/yiming/anaconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/yiming/nerfstudio/scripts/train.py", line 248, in entrypoint
    main(
  File "/home/yiming/nerfstudio/scripts/train.py", line 234, in main
    launch(
  File "/home/yiming/nerfstudio/scripts/train.py", line 173, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/yiming/nerfstudio/scripts/train.py", line 88, in train_loop
    trainer.train()
  File "/home/yiming/nerfstudio/nerfstudio/engine/trainer.py", line 152, in train
    self.pipeline.datamanager.train_dataparser_outputs.save_dataparser_transform(
  File "/home/yiming/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SemanticDataManager' object has no attribute 'train_dataparser_outputs'
```

**Comment by penguinflys** [comment]
Hey, @tancik Why don't we set the `DataparserOutputs.save_dataparser_transform()` to `DataParser.save_dataparser_transform()` class, I think this is a better solution, because 
* There is no need to store a instance variable `train_dataparser_outputs` in `DataManager` anymore, and code can be cleaner, alternatively you can call `self.pipeline.datamanager.train_dataparser.save_dataparser_transform` in `trainer.py`
* `DataParser` make sense to have a `save_dataparser_transform()`, as you can save the transform params during setup of training.

I am not sure if the independence between modules would be affected, at least I didn't see any.

**Comment by tancik** [comment]
@penguinflys That seems like a good idea to me. Feel free to submit a PR.

**Comment by penguinflys** [comment]
> @penguinflys That seems like a good idea to me. Feel free to submit a PR.

will do 😉

**Comment by penguinflys** [comment]
By the way, I have seen that there are many loss computed in the `get_metrics_dict` function, which should be calculated in loss function. would you mind if I swap the order to calculate loss first then metrics?

if you search all the references `get_loss_dict` you can find that most of times that metrics_dict is useless taking a place in the function variable. I think it should be removed by computing the `loss_dict` first.

what is you opinion? @tancik

**Comment by tancik** [comment]
@penguinflys I'm not sure that I follow. Can you provide some example changes that you would want to make.
