### ISSUE TITLE
Using images with different sizes

### ISSUE THREAD

**Issue by wuzirui** [nerfstudio-project/nerfstudio#1213]
**Describe the bug**
It seems in #868 that nerfstudio now supports training nerf with images of different sizes. Still, the following error popped up when I was trying to train nerf on the Waymo Open dataset (with images of size 1920x1080 and 1920x886).

**To Reproduce**
here is my `transforms.json`:
```json
{
    "camera_model": "OPENCV",
    "k1": 0,
    "k2": 0,
    "p1": 0,
    "p2": 0,
    "frames": [
        {
            "transform_matrix": [
                [ 0.9867326702177505, -0.07891035227867108, 0.14188655266868724, -1220.8189424581687 ],
                [ 0.0712640838307024, 0.9957584074065905, 0.058194711399413526, 10554.48731853961 ],
                [ -0.14587689289506664, -0.04731120778786397, 0.9881708261919773, 16.831 ],
                [ 0.0, 0.0, 0.0, 1.0 ]
            ],
            "./image_0/0000000.png",
            "fl_x": 2059.612,
            "fl_y": 2059.612,
            "cx": 952.4122,
            "cy": 634.5872,
            "w": 1920,
            "h": 1280
        },
        ...
     ]
}
```

**Expected behavior**
```bash
RuntimeError: stack expects each tensor to be equal size, but got [886, 1920, 3] at entry 0 and [1280, 1920, 3] at entry 3
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7344146/211270923-5eec7335-ff81-4464-abd3-91b91422ccf6.png)

**Comment by jake-austin** [comment]
Any chance you can send me the command you're using to do this? I ask because right now, the only ns-train method that supports multiple camera sizes is the phototourism method, since the collate function we use is specified by the datamanager, with the VariableResDataManagerConfig being the only variation of the vanilla configuration with the collate function that will concatenate images by putting them in a list instead of stacking the raw tensors.

If you're just using the vanilla datamanager, a quick hack to get this to work rn would be to go into the method_configs.py file, and define your own method that is the same as nerfacto or whatever you're planning on using, except you replace the VanillaDataManagerConfig with a VariableResDataManagerConfig (which is simply a subclassed version of the VanillaDataManagerConfig, but with again a collate that will collate by putting images in a list).

**Comment by wuzirui** [comment]
I am using the vanilla DataManager. I will try with the configs. Thank you very much!

**Comment by jake-austin** [comment]
Party! Let me know if you have any issues with the variable res config, make sure to look at the phototourism method in the method_configs.py file for reference

**Comment by yzslab** [comment]
Replace  [the line 107 in nerfstudio/data/utils/nerfstudio_collate.py](https://github.com/nerfstudio-project/nerfstudio/blob/8c41a263b8c9aaba2ed242d0abaf03480a50eb1d/nerfstudio/data/utils/nerfstudio_collate.py#L107) with `return batch` seems work well on variable size images.

**Comment by qhdqhd** [comment]
> VariableResDataManagerConfig

It really works, thank you!

**Comment by qhdqhd** [comment]
> [将nerfstudio/data/utils/nerfstudio_collat​​e.py 中的第 107 行](https://github.com/nerfstudio-project/nerfstudio/blob/8c41a263b8c9aaba2ed242d0abaf03480a50eb1d/nerfstudio/data/utils/nerfstudio_collate.py#L107)替换 为`return batch`似乎在可变大小图像上运行良好。

It really works, thank you!
