### ISSUE TITLE
Cant create checkpoint

### ISSUE THREAD

**Issue by AndrewAndreevich** [nerfstudio-project/nerfstudio#1221]
Sorry, i cant find the option for create checkpoints after train model, how to do that ?

**Comment by ptc-lexvandersluijs** [comment]
I have the same question. It would be great not to have to re-train every time the program is started. Am I overlooking something?

**Comment by ptc-lexvandersluijs** [comment]
Update: I have found the solution: a checkpoint is actually automatically created, but you have to instruct the viewer to load it. This is described on this page: https://docs.nerf.studio/en/latest/quickstart/first_nerf.html . There is a small error in the instruction though, probably because the parameter syntax has changed since the documentation was written. The parameter isn't "--load-dir" but "--trainer.load-dir"

Putting it all together, here is the command line that works for me, which is called from the project's root folder. Of course you will have to change the name of the folder where the checkpoint data (.ckpt file) resides.

`ns-train nerfacto --data data/nerfstudio/poster --trainer.load-dir outputs/data/nerfstudio/poster/nerfacto/2023-01-12_090611/nerfstudio_models --viewer.start-train False`

**Comment by tancik** [comment]
Closing, feel free to reopen if it is still and issue.
