### ISSUE TITLE
No such file or directory: 'data/nerfstudio/poster/transforms_train.json'

### ISSUE THREAD

**Issue by WithFoxSquirrel** [nerfstudio-project/nerfstudio#1614]
I use tensoRF to train, cmd "ns-train tensorf --data data/nerfstudio/poster",
anyway "ns-train instant-ngp --data data/nerfstudio/poster" and "ns-train nerfacto --data data/nerfstudio/poster" is correct.

following error info:

  File "/home/kuiper/work/08-xr/animal/nerfstudio/nerfstudio/data/dataparsers/base_dataparser.py", line 137, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split)
  File "/home/kuiper/work/08-xr/animal/nerfstudio/nerfstudio/data/dataparsers/blender_dataparser.py", line 71, in _generate_dataparser_outputs
    meta = load_from_json(self.data / f"transforms_{split}.json")
  File "/home/kuiper/work/08-xr/animal/nerfstudio/nerfstudio/utils/io.py", line 30, in load_from_json
    with open(filename, encoding="UTF-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/nerfstudio/poster/transforms_train.json'

**Comment by SamBahrami** [comment]
How did you solve this

**Comment by SamBahrami** [comment]
If anyone else was wondering why this issue comes up, its because by default tensorf uses "blender_data" which is a different format. If you want to train the poster demo, you can append `nerfstudio-data` to the end of your command, and it should work.

so the command `ns-train tensorf --data data/nerfstudio/poster nerfstudio-data` should work.
