### ISSUE TITLE
Is there a BaRF Implementation?

### ISSUE THREAD

**Issue by jytime** [nerfstudio-project/nerfstudio#1691]
**Is your feature request related to a problem? Please describe.**
Hello, thank you for the great and east-to-use repository!

I have been working with some initial camera poses for a sequence and, while they are almost correct, they are not highly accurate. For instance, the rotation matrix has an average rotation difference of 5-10 degrees compared to the ground truth one.

I came across the --pipeline.datamanager.camera-optimizer.mode SO3xR3 flag in nerfstudio, which I understand is used for optimizing camera poses. After reading through issue https://github.com/nerfstudio-project/nerfstudio/issues/1017, I realized that the camera optimizer in nerfstudio is not the same as [BaRF](https://github.com/chenhsuanlin/bundle-adjusting-NeRF).

I have two questions that:

- Do we now have an implementation in nerfstudio that is more closely aligned with the BaRF method? If so, could you please guide me on how to use it?
- If not, do you think that the current camera optimizer in nerfstudio would be sufficient for handling the poses with an average rotation error of 10 degrees?

Thank you for your assistance :)

**Describe the solution you'd like**
It would be best if I can implement something close to BaRF by setting a few flags.

**Comment by maturk** [comment]
We have implemented a few BARF algorithms here [BARF-nerfstudio](https://github.com/maturk/BARF-nerfstudio).

**Comment by maturk** [comment]
@f-dy, I don't think so, because their performance is quite unpredictable. When BARF style annealing, e.g. using barf-grad, is turned on, due to the coarse-to-fine kind of optimization strategy you loose some high frequency details during optimization if you already have decent COLMAP poses for your dataset (which is most often the case). From my experimentation, these BARF methods are good at recovering your scene when you have really bad poses (which is not often the case with users of Nerfstudio). I have yet to see a method that could replace colmap and recover the scene and as well as pose estimates simultaneously.

**Comment by f-dy** [comment]
Ok, that confirms my previous insights on the method. The "BA" part of BARF is lying a bit anyway, because I don't think bundle adjustment problems can be solved by SGD. Read [Triggs et al. 2000](https://inria.hal.science/inria-00548290v1) for a full explanation. I expect, however, to have real BA with Gaussian splats anytime soon (using Levenberg-Marquardt rather than SGD)
