### ISSUE TITLE
Blurry Nerfacto results

### ISSUE THREAD

**Issue by MvWouden** [nerfstudio-project/nerfstudio#1850]
**Describe the issue**
Nerfacto keeps resulting in blurry results/renders even when:
- Changing up the use of COLMAP or custom camera parameter imports with camera optimizer
- Changing up datasets in terms of scenes (car outdoor, indoor, object focused, etc.), way of capturing (walk around, turntable) 
- Trying out different resolutions of images as "largest" image size (4k vs 1080p vs 1536px vs 800px)
- Trying out different amount of images used in training (100 vs 200 vs 500)
- Ensuring there is good lighting, slow capture, blurry images are filtered out etc.

With blur, I do not mean the generation of floaters since that's to be expected, but rather the sharpness/quality of the texture of the objects.

Is there something going wrong, or are there any parameters I can tweak to further increase the "sharpness" of my models?

**To Reproduce**
Training command used, e.g.:
```
ns-train nerfacto --data <path/to/data> --vis tensorboard --experiment_name <exp_name> --timestamp <timestamp_name> --viewer.quit-on-train-completion True --pipeline.model.predict-normals True --pipeline.datamanager.train-num-images-to-sample-from 250 --pipeline.datamanager.eval-num-images-to-sample-from 10 --pipeline.datamanager.eval-num-rays-per-batch 1024
```

Render command used (generated by ns-viewer):
```
ns-render --load-config <path/to/config> --traj filename --camera-path-filename <path/to/file> --output-path <path/to/out>
```

**Expected behavior**
Given the quality of the capture/dataset, I expect the nerfacto renders to be relatively sharp.

**Screenshots**

Example image of dataset 1 (COLMAP used):
![frame_00010](https://user-images.githubusercontent.com/56082205/235618624-3b7fd56f-0048-4735-a178-3622de8a9174.png)

Example image of dataset 2 (Custom Pose Import used):
![frame_00010](https://user-images.githubusercontent.com/56082205/235618457-5564a706-0ab0-4d1c-96a0-21fb34755d29.jpeg)

Example render of dataset 1: https://user-images.githubusercontent.com/56082205/235618905-96092129-8f74-4b8f-be94-21c854989eed.mp4

Example render of dataset 2: https://user-images.githubusercontent.com/56082205/235618471-fa96f22c-b359-42ce-aad9-c1688038eb10.mp4

**Environment**
| What | Value |
|--------|--------|
| Platform | Windows |
| Nerfstudio version | Latest Source (1st of  May 2023) |
| Python version | 3.10.5 |
| CUDA version | 11.7 | 
| PyTorch version | 1.13.1+cu117 |

**Additional Context**
Given that I've seen sharper renders created by others, I tried improving and varying the capture setup to see if the blur is down to that.
Unfortunately, it seems that even with good capture conditions, results stay like this. 

Edit: If there are any commands I can run to give more information, please let me know.

**Comment by MvWouden** [comment]
I've just got a feeling that it may be caused by the camera optimizer, so I'll try to get a run in without camera optimization to test.

**Comment by MvWouden** [comment]
> Can you post images of the reconstructions?

You should be able to see the rendered videos that I attached. If you would like other renders or  screenshots, please let me know which ones.

**Comment by tancik** [comment]
Oh sorry, I missed those. The quality on the car isn't that far off from what I would expect. What camera are you using?

**Comment by MvWouden** [comment]
> Oh sorry, I missed those. The quality on the car isn't that far off from what I would expect. What camera are you using?

Simple iPhone 13 camera. If the quality on the car is expected, then that's my bad. I've compared it to renders of others that feature similar scenes, from which I assumed they used either instant-ngp or nerfacto.

With regards to the other scene, do you have any suggestions as to what's going wrong?

**Comment by MvWouden** [comment]
I have another render of dataset 2 where the camera optimizer was disabled (during training) to check whether that was the issue (it seemed not to be): https://user-images.githubusercontent.com/56082205/235739925-00b2de34-b9b0-43f3-90b5-6048af9d3ee8.mp4

The lines of the ChArUco markers seem sharp while the object contours are not, which is odd.

**Comment by tancik** [comment]
The solid colors (the white of the paper, and the black of the charuco markers) will cause these foggy artifacts. Try capturing the scene on a textured surface (carpet, dirt, ect)

**Comment by MvWouden** [comment]
> The solid colors (the white of the paper, and the black of the charuco markers) will cause these foggy artifacts. Try capturing the scene on a textured surface (carpet, dirt, ect)

Alright, thanks for the help! I'll capture some new scenes to test it out.

At the same time, I was also wondering, are there any parameters I could try to tweak to increase the perceived resolution and sharpness of the model?

**Comment by tancik** [comment]
You could try using the `nerfacto-big` model.

**Comment by neekolas** [comment]
I am also running into this issue for indoor room captures.

I've tried imports from Record3D, Polycam, and just a slow walking video. All taken with an iphone using a gimbal to reduce blur. Tried with nerfacto, nerfacto-big, and instant-ngp.

One hypothesis I have is that there needs to be better selection on source images. Just chopping the video to 4ps using FFPMEG feels like we are not setting the model up for success. If even 5% of the source images are blurry because the selected frames happened during camera motion, that might be enough to taint the whole model.

Has anyone been experimenting with doing some OpenCV pre-processing of the input frames to select for the least blurry images?

**Comment by HungNgoCT** [comment]
> The solid colors (the white of the paper, and the black of the charuco markers) will cause these foggy artifacts. Try capturing the scene on a textured surface (carpet, dirt, ect)

Hi @tancik 

Could you please share the reasons why solid colors (white and black) cause foggy artifacts? Do other colors such as blue, yellow are fine?

I ask for help on this because I also have a problem when I use sdfstudio for testing. I captured a set of a white table with chairs as the images below. Mesh reconstruction for chair is good while the one for white table is poor. From results for chair, I think there was no problem for camera pose estimation. I think it relates to color as your comments here, but cannot understand reasons. Highly appreciate for your help to understand this.

![image](https://user-images.githubusercontent.com/110378166/236378735-769c9eb4-d706-4ca3-a19b-64f624f7cebc.png)

Also, I did render my school office, result was so poor with foggy artifacts. Do you have any advice on this (Note: I use nerfacto-big for training with 1200 images)

https://user-images.githubusercontent.com/110378166/236379218-403dd20d-e05d-4436-9d54-a67f1ef72572.mp4

**Comment by MvWouden** [comment]
> I am also running into this issue for indoor room captures.
> 
> 
> 
> I've tried imports from Record3D, Polycam, and just a slow walking video. All taken with an iphone using a gimbal to reduce blur. Tried with nerfacto, nerfacto-big, and instant-ngp.
> 
> 
> 
> One hypothesis I have is that there needs to be better selection on source images. Just chopping the video to 4ps using FFPMEG feels like we are not setting the model up for success. If even 5% of the source images are blurry because the selected frames happened during camera motion, that might be enough to taint the whole model.
> 
> 
> 
> Has anyone been experimenting with doing some OpenCV pre-processing of the input frames to select for the least blurry images?

Yes I have done a custom selection of images to filter out the blurry frames. Could be slightly helpful, but still ends up with roughly the same result.

**Comment by takeru** [comment]
I am also trying to get a clean output.
If possible, can you provide me with the original data set?
If I find a condition that works, I will share it with you.

**Comment by MvWouden** [comment]
Will close this issue since it's mainly due to capture conditions and sensitivity to hyperparameters, not nerfacto itself.
