### ISSUE TITLE
Temporal TV loss test is failing

### ISSUE THREAD

**Issue by tancik** [nerfstudio-project/nerfstudio#1953]
Related to #1952 

Running `model.get_temporal_tv_loss()`
produces the following error,
```
Traceback (most recent call last):
  File "/projects/pyrad/tests/field_components/test_temporal_grid.py", line 47, in <module>
    test_temporal_grid()
  File "/projects/pyrad/tests/field_components/test_temporal_grid.py", line 41, in test_temporal_grid
    model.get_temporal_tv_loss()
  File "/projects/pyrad/nerfstudio/field_components/temporal_grid.py", line 364, in get_temporal_tv_loss
    assert False, (self.embeddings[:, feat_idx[0]] - self.embeddings[:, feat_idx[1]]).abs().mean().shape
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

Assigning to @lsongx as you probably have the best idea of what is going wrong.

**Comment by brentyi** [comment]
This might be my fault? https://github.com/nerfstudio-project/nerfstudio/pull/1944/commits/6464261940f578943c193d7b85688e34f11af62d

**Comment by lsongx** [comment]
This is caused by a recent PR (https://github.com/nerfstudio-project/nerfstudio/commit/f481f5ebec847a9d6781f090602cc9bebf47cf23#r114167279). 
I am not sure if I should fix this with a new PR, as I am preparing to move nerfplayer out as suggested. 
My current plan is that I should remove these:
- `field_components/cuda`
- `field_components/temporal_grid.py`
- `fields/nerfplayer_nerfacto_field.py`
- `fields/nerfplayer_ngp_field.py`
- `models/nerfplayer_nerfacto.py` 
- `models/nerfplayer_ngp.py`
- `tests/field_components/test_temporal_grid.py`

Any comments?

**Comment by tancik** [comment]
@lsongx That sounds good
