### ISSUE TITLE
Blurry in Poster

### ISSUE THREAD

**Issue by panyuanzhi** [nerfstudio-project/nerfstudio#2084]
Hello, I follow the step in https://docs.nerf.studio/en/latest/quickstart/first_nerf.html.and I get a blurry image.
![image](https://github.com/nerfstudio-project/nerfstudio/assets/12220654/7d3e3c37-a137-46ac-b65a-f7d8ea902c17)

Is this Normal? or How can i make it clear?

**Comment by maturk** [comment]
The region "looking outside" is expected to be blurry. This dataset is meant to really only reconstruct the chair/poster since its a "outwards looking in" dataset, so the quality will be focused on the object being scanned. The quality of the chair/poster is what is expected. You can increase quality by increasing --pipeline.datamanager.train-num-rays-per-batch

**Comment by panyuanzhi** [comment]
> The region "looking outside" is expected to be blurry. This dataset is meant to really only reconstruct the chair/poster since its a "outwards looking in" dataset, so the quality will be focused on the object being scanned. The quality of the chair/poster is what is expected. You can increase quality by increasing --pipeline.datamanager.train-num-rays-per-batch

Thanks for your answer.
