### ISSUE TITLE
Good practices, tips and benchmarks (to obtain better results)

### ISSUE THREAD

**Issue by Naurk** [nerfstudio-project/nerfstudio#2281]
Not really an issue or a request, and please forgive me if this is inappropriate, but I wonder if there is a repository of good practices, useful tips, and complete examples (apart from the poster) for achieving high-quality results from image capture.

I've only worked with a few NeRFs, but I've noticed significant differences in the output results. Apart from using appropriate models and adhering to basic image suggestions (such as avoiding blurred, over or underexposed images, etc.), do you think it would be beneficial to compile some technical tips for capturing good images to obtain better data? For example, determining the minimum number of images per degree of rendering, finding the optimal image resolution range to make distinctions per model, and suggesting appropriate field of view (FOV) for different contexts.

These tips can be gathered in various ways, such as combining data types with output examples and/or benchmarks. This way, novices like me can understand if they are using inadequate data or making mistakes during training, as well as selecting inappropriate models, etc. For instance, I haven't grasped the extent to which image resolution and format impact the final results, or when it's preferable to use a video instead of multiple photos, or how to properly choose the bounding box size beyond the standard 8.

Thank you.

**Comment by kerrj** [comment]
There's a channel in discord for capture tips which might help you! Making a capture tutorial has been on our radar for some time now, we just haven't gotten around to it yet. In my experience the most important thing for captures is the distribution of viewpoints being wide enough to cover all relevant parts of the scene with a good surrounding of camera views. Resolution doesn't matter too much, higher camera FOV generally give better results because they result in more views of the scene (easier to capture), and motion blur has a noticable degrading effect if there's a lot of motion blur. 

In terms of best practices for training, unless you're doing something fancy I would just stick with nerfacto or nerfacto-huge if you have the GPU memory, a lot of the scene crop setting and parameters there have been tuned to work out of the box on most cases.
