### ISSUE TITLE
Sampling points based on depth information

### ISSUE THREAD

**Issue by Saixiaoma** [nerfstudio-project/nerfstudio#2499]
I want to use depth information to limit the sampling range to a depth value when sampling on a pixel ray. How should I do this?

**Comment by maturk** [comment]
What came to mind is simple back projection. So instead of casting rays like (X,Y,Z) = origins + t * directions for t in different steps, you could simply do backprojection using the inverse intrinsics matrix, and c2w matrix. So basically take the inverse of the projection transformation and you will get X,Y,Z locations based on your known depths and you could only sample those points. You could also modify the ray casting and only sample t values near your depth. Currently there is no ready implementation for this however.

**Comment by Saixiaoma** [comment]
Thank you very much!

I'm modifying ray casting and only sample t values near my depth, but I have some questions.
In the generate_ray_samples function in the ray_samplers.py file, I already know the depth information of each point and the distance in the ray direction, how should I calculate bins and euclidean_bins.
For example, the distance of a point is d, and I want to sample within a certain range. bins, euclidean_bins, ray_bundle.nears, and ray_bundle.fars are calculated as follows:

d_min = 0.9 * d * scale # where scale is in dataparser_transforms.json
d_max = 1.1 * d * scale # where scale is in dataparser_transforms.json
bins = torch.linspace(d_min,d_max,num_samples+1).to(ray_bundle.origins.device)[None,...]
ray_bundle.nears = d_min
ray_bundle.fars  = d_max
euclidean_bins   = spacing_to_euclidean_fn(bins)

I want to know how the scale information in the physical sense is converted into the space in the NeRF sampling process.
