### ISSUE TITLE
Impossible to connect to webviewer

### ISSUE THREAD

**Issue by ArpegorPSGH** [nerfstudio-project/nerfstudio#2740]
**Describe the bug**
When training a model or loading a checkpoint, the given viewer address do not lead to any page.

**To Reproduce**
1. Train a model
2. Ctrl + Click on the address of the viewer
3. A blank page with the error message : "This webpage in unreachable" opens

**Expected behavior**
The webviewer should open.

**Additional context**
The given address seems to be wrong. It is by default : "http://0.0.0.0:7007".
This only happens when installing from source. It works fine with pip install.

**Comment by brentyi** [comment]
Yeah, we should make this clearer. It's currently the host address the server is listening to, which is not necessarily a valid IP address: https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost

**Comment by ArpegorPSGH** [comment]
But will this be solved shortly? Because I want to implement my own models, but also pull from source the latest features and merge them with Git, without having to sort everything manually.

**Comment by cvachha** [comment]
Try going to http://localhost:7007/ for the viewer, this seems to work on Windows

**Comment by brentyi** [comment]
Yeah, the server should be accessible by connecting to whatever machine you're running on. If you're running locally `http://localhost:7007` should work (as pointed out by @cvachha), if you're running on a remote server (assuming no firewalls) and you know IP address you can also connect to `http://that_ip:7007`, for SSH a common practice is also just to forward the port: https://docs.nerf.studio/quickstart/viewer_quickstart.html#training-on-a-remote-machine

As an experimental thing, you can also pass in `--viewer.make-share-url True` and you should get a publically accessible https URL at `https://[some random string].share.viser.studio`.

**Comment by brentyi** [comment]
> But will this be solved shortly? Because I want to implement my own models, but also pull from source the latest features and merge them with Git, without having to sort everything manually.

This is actually working as designed; `0.0.0.0` is the host address that the webserver is bound to. It's just a bad design because this isn't an IP address that you can necessarily connect to... we should print something clearer, but the fix wouldn't impact your ability to connect to the viewer.

The server should still be accessible by connecting to whatever machine you're running on. If you're running locally `http://localhost:7007` should work (as pointed out by @cvachha), if you're running on a remote server (assuming no firewalls) and you know IP address you can also connect to `http://that_ip:7007`, for SSH a common practice is also just to forward the port: https://docs.nerf.studio/quickstart/viewer_quickstart.html#training-on-a-remote-machine

As an experimental thing, you can also pass in `--viewer.make-share-url True` and you should get a publically accessible https URL at `https://[some random string].share.viser.studio`.

**Comment by ArpegorPSGH** [comment]
Just having to click on the link in the console definitely makes things smoother.

**Comment by liuxj1** [comment]
> Try going to http://localhost:7007/ for the viewer, this seems to work on Windows

Why does a blank screen appear when I click

**Comment by cvachha** [comment]
> > Try going to http://localhost:7007/ for the viewer, this seems to work on Windows
> 
> Why does a blank screen appear when I click

If you are running ns-train and running locally at port 7007, the page should take you to the viewer
