### ISSUE TITLE
How can i get background removed result?

### ISSUE THREAD

**Issue by hanjoonwon** [nerfstudio-project/nerfstudio#2802]
I don't want to reconstruct the background, just the object.
 Which pipeline option should I use to achieve the desired result?

**Comment by maturk** [comment]
For the nerf models, like nerfacto, just make sure you add masks when training. [Here](https://docs.nerf.studio/quickstart/data_conventions.html#masks) you can read more about the mask conventions in nerfstudio. For gsplatfacto/gaussian-splatting the masks are a bit hacky right now, making the gaussians within the masked out regions just black so you could try remove them as a post-processing step.

**Comment by anniezhang2288** [comment]
You can also try Nerf-in-the-wild to change the background of the NeRF since it has appearance embeddings for it.

**Comment by KuangenZhang** [comment]
> I don't want to reconstruct the background, just the object. Which pipeline option should I use to achieve the desired result?

From my understanding, you can set the background color to (0, 0, 0) directly. Since the default color for empty regions is (0, 0, 0), setting the background in your images to this value will make the predicted and ground truth colors identical. As a result, the gradient in the background region will be zero, preventing Gaussian Splatting from learning anything in those areas.

```
bg_color = [1, 1, 1] if dataset.white_background else [0, 0, 0]
```
