### ISSUE TITLE
Export point clouds from nerfacto in the real size of the objects

### ISSUE THREAD

**Issue by JE199903** [nerfstudio-project/nerfstudio#3007]
Is it possible to export point clouds from NeRfs which where trained with the nerfacto method in the real size of the objects?

I want to use the point clouds to compare a digital model and the real object by comparing their point clouds via ICP-algorithms. At the moment the exported point clouds haven´t the real size of the objects which makes a comparison of the models difficult. If I scale the exported point cloud from the NeRF manually it get´s too inaccurate for a comparison with the digital model.

**Comment by JE199903** [comment]
I think they should be. Is there any way to check it?

The problem appears when I use COLMAP for the camera pose estimation and also with polycam and an Ipad pro with LIDAR-Scanner. Also the sizes of the trained NeRfs is different each time and there is no constant scale I have to apply to get the real measurements of the objects.

**Comment by maturk** [comment]
Yes it is better to use the polycam app with depth data. Okay so, the problem with COLMAP is that it will never give you metrically correct poses, they are only relatively correct up to a scaling factor. So they are not in the same coordinate system as your captured object and hence the scale will be off. But I think if you use polycam, it will use the depth data so solve for the scale ambiquity and the poses will be metrically correct. Problem now is that when you use nerfacto, it will squeeze all your poses to a -1,1 unit box due to various reasons. After training the nerf and exporting the pointcloud, you need to invert this transformation on your poses. The transformation matrix is stored in a file called "dataparse_transforms.json" and is found in the same folder as your model config.yml file is. So just apply the inverse of this transform to your point cloud and it should be metrically back to the coordinate frame of you poses, that is, if your poses are in the correct scale to begin with. Many similar issues have been made regarding this topic [here](https://github.com/nerfstudio-project/nerfstudio/issues/1606#issuecomment-1588532533), and [here](https://github.com/nerfstudio-project/nerfstudio/issues/2924).
