### ISSUE TITLE
Docker torch version should be updated from 2.0.1

### ISSUE THREAD

**Issue by maturk** [nerfstudio-project/nerfstudio#3235]
Hi,

I am not a Docker user, but the torch version should be bumped up to 2.1.2 + [here](https://github.com/nerfstudio-project/nerfstudio/blob/2e3c3c179a4cbfba96c6ecfa6a9d1bb3d21dc569/Dockerfile#L135). Would make a PR myself but I am a Docker noob.

**Comment by rowellz** [comment]
I can give this a try. I’ve been working with nerfstudio exclusively through docker containers for a few months now, so i can verify when  I hopefully get it working. Thanks again for your help over the weekend!

**Comment by maturk** [comment]
> I can give this a try. I’ve been working with nerfstudio exclusively through docker containers for a few months now, so i can verify when I hopefully get it working. Thanks again for your help over the weekend!

Thanks for the help @rowellz, I appreciate it.

**Comment by rowellz** [comment]
@maturk I failed to mention earlier that I've been running nerfstudio via `docker-compose`, which is my preferred method of managing and running docker containers. The official [nerfstudio docs](https://docs.nerf.studio/quickstart/installation.html#use-docker-image) only show support for the `docker run` command. 

This lead me to tweaking the existing `.devcontainer/docker-compose.yml` file, which hasn't been touched in over a year. I can confirm that I was able to run `ns-process-data` video followed by `ns-train splatfacto` after running `docker-compose up`.  Here is the link to the diff of my [forked repo](https://github.com/nerfstudio-project/nerfstudio/compare/main...rowellz:nerfstudio:main) 

It is going to take me some more time to resolve the versioning for the root Dockerfile, since I don't use `docker run`. But if anyone is eager to get gsplat 1.0.0 running in a docker container, my forked repo linked above will support it at the moment.

**Comment by rowellz** [comment]
I am probably going to have to wave the white flag on trying to update the root Dockerfile, my apologies @maturk. I noticed on DockerHub that nerfstudio 1.1.3 was pushed, so I tried simplifying my forked repo by referring to the `dromni/nerfstudio:1.1.3` image directly in the `docker-compose.yml` file. I unfortunately ran into the same issue [here](https://github.com/nerfstudio-project/nerfstudio/issues/2878#issuecomment-2151289371)

The good news is the solution that @jkulhanek offered in that discussion still works, and is how I got my forked repo working with `gsplat 1.0.0` in the first place. If there is any interest in adding `docker-compose` to the nerfstudio docs, let me know, I'd be happy to contribute.

**Comment by jkulhanek** [comment]
Hi, sorry for the delay. I plan to integrate custom docker images soon

**Comment by jb-ye** [comment]
This is what we should prioritize. I have seen multiple users saying gsplat 1.0 is compatible with torch 2.0. 

Can you help? @Zunhammer I believe we also need to update torchvision version.

```
pytorch==2.1.2 torchvision==0.16.2
```

**Comment by Zunhammer** [comment]
Yeah sure, I added a PR for this.

Chaning the version is actually quite easy (see PR). Additionally, we need to take care of the setuptools version (below 70) and we need to remove the pinning of tinycudann as the version 1.6 is not compatible with the new torch version.

Let me know if you need any further assistance
