### ISSUE TITLE
Support for individual intrinsics? (feature request)

### ISSUE THREAD

**Issue by pooncs** [nerfstudio-project/nerfstudio#775]
Hi I was wondering if there is any plans to include individual camera intrinsics, while keeping backwards compatibility to the current transforms.json file, as with instant-ngp?
That'll be helpful for training on images in the wild, where the camera resolution and intrinsics are different.

**Comment by ethanweber** [comment]
Good request! @jake-austin has been working on this right now. Maybe you can comment on the state of this feature?

**Comment by jake-austin** [comment]
Just about there. All on the CamerasV2 branch. Last night I think I about cracked it, I just need to write more exhaustive and stress tests and make sure that I'm correctly processing all combinations of inputs to the generate_rays() function and whatnot. Also need to resolve some weird viewer issues since it was training correctly last night, just the viewer wasn't showing the model itself.

**Comment by tancik** [comment]
Added documentation in #1246
