### ISSUE TITLE
Dynamic NeRF

### ISSUE THREAD

**Issue by Triocrossing** [nerfstudio-project/nerfstudio#813]
Hello, 

I wish to first present my appreciation to all the contributors for sharing and hardworking on this project.

I am wondering if there is any future plan on including **dynamic NeRF methods** into your projects (e.g. DNeRF, HyperNeRF .etc)?

Best regards,

**Comment by w-m** [comment]
It looks like @JulianKnodt might be working on dynamic NeRF methods: https://github.com/nerfstudio-project/nerfstudio/pull/815 ?

**Comment by JulianKnodt** [comment]
@w-m I won't commit to implementing D-NeRF, but am starting to mess around with related things.

**Comment by JulianKnodt** [comment]
An implementation for D-NeRF was just merged. It can be run with
`ns-train dnerf dnerf-data`
@Triocrossing

**Comment by liuxin2322** [comment]
> 
Great！how can i process my own custom data(dynamic scene) using nerfstudio ?

**Comment by JulianKnodt** [comment]
@liuxin2322, I received your email, and it may be useful to create a new issue.

Please specify what data you have, and what information is available.
- This is probably the most important, since if all you have is a video without annotated positions, it isn't compatible with D-NeRF currently. Otherwise, if you're using blender or something to generate a video, then it may be possible to write a script for it.

Also specify your general goal (I assume you want to be able to reconstruct data with D-NeRF).

I haven't worked on NeRFStudio for a bit, but if it's clear what steps need to be done then it'll be easier for another contributor to work on it.
