### ISSUE TITLE
Cameras with different paramters (intrinsics / distortion ...)

### ISSUE THREAD

**Issue by nikmo33** [nerfstudio-project/nerfstudio#868]
**Is your feature request related to a problem? Please describe.**
Having support for cameras with various intrinsics etc. allows for training with imags from the wild as well as multi-camera rigs. Upon initial inspection it seems quite straight forward to do so, and so was wondering if there was something I was missing. I am happy to take up this feature request and make a PR.

**Describe the solution you'd like**
Support two types for inputs to constructer of Camera class. Either a float or a tensor of dim [num_cameras, ...].  In case backwards compatibility is important also support singelton tensors
**Describe alternatives you've considered**

**Additional context**

**Comment by tancik** [comment]
Take a look at #648, it might have what you are looking for. If you happen to try it out, let us know if it works for you.

**Comment by nikmo33** [comment]
> #648

It seems like there is an intermediate solution? A simple post-processing step for most datasets such that images are of the same h,w is quite feasible, or this can even be put into the InputDataset if not. Although supporting variable camera parameters seems quite straight forward. I was wondering what the reason behind these checks like these  are ? Seems like if we just remove these and pass the correct shapes of [num_cams, ...] everything works fine? 
```
assert torch.all(
                cy == (cy[0] if cy.ndim > 0 else cy.item())
            ), "Batched cameras of different types will be allowed in the future."
```

**Comment by jake-austin** [comment]
The reason we did this was more so that it was untested behavior. Prior to release, all the camera intrinsics that weren't focal length (cx, cy, etc) were all just represented by one scalar each that was shared for all cameras in the batch. As a buzzer beater before release I was trying to push through my updated cameras PR to get all this working for camera batches of different height / widths / cx / cys, but was running into some issues getting it done in time for release, so we compromised and just updated the types backing the Cameras class without actually fully supporting these kinds of batched cameras more so to prevent large changes to the Cameras class post-release when we could fully test / work out any bugs and then remove these guardrails.

I think in my PR for cameras, everything is now working and tested and the guardrails have been removed, and you can even generate rays for multiple full images that have different heights and widths. The last thing I'm waffling on before merging this in is perhaps building up a little infra around this change so ppl have easy options for building these kinds of datasets with different intrinsics

**Comment by nikmo33** [comment]
> The reason we did this was more so that it was untested behavior. Prior to release, all the camera intrinsics that weren't focal length (cx, cy, etc) were all just represented by one scalar each that was shared for all cameras in the batch. As a buzzer beater before release I was trying to push through my updated cameras PR to get all this working for camera batches of different height / widths / cx / cys, but was running into some issues getting it done in time for release, so we compromised and just updated the types backing the Cameras class without actually fully supporting these kinds of batched cameras more so to prevent large changes to the Cameras class post-release when we could fully test / work out any bugs and then remove these guardrails.
> 
> I think in my PR for cameras, everything is now working and tested and the guardrails have been removed, and you can even generate rays for multiple full images that have different heights and widths. The last thing I'm waffling on before merging this in is perhaps building up a little infra around this change so ppl have easy options for building these kinds of datasets with different intrinsics

That makes sense! Ive switched to your branch and everything seems to work fine (including viewer) so thanks! Was just curious since after commenting out those lines everything worked as well! Anywho thanks for the feature!

**Comment by nikmo33** [comment]
> The reason we did this was more so that it was untested behavior. Prior to release, all the camera intrinsics that weren't focal length (cx, cy, etc) were all just represented by one scalar each that was shared for all cameras in the batch. As a buzzer beater before release I was trying to push through my updated cameras PR to get all this working for camera batches of different height / widths / cx / cys, but was running into some issues getting it done in time for release, so we compromised and just updated the types backing the Cameras class without actually fully supporting these kinds of batched cameras more so to prevent large changes to the Cameras class post-release when we could fully test / work out any bugs and then remove these guardrails.
> 
> I think in my PR for cameras, everything is now working and tested and the guardrails have been removed, and you can even generate rays for multiple full images that have different heights and widths. The last thing I'm waffling on before merging this in is perhaps building up a little infra around this change so ppl have easy options for building these kinds of datasets with different intrinsics

That makes sense! Ive switched to your branch and everything seems to work fine (including viewer) so thanks! Was just curious since after commenting out those lines everything worked as well! Anywho thanks for the feature!

**Comment by jake-austin** [comment]
@nikmo33 If you can lmk if you encounter any weirdness please please lmk, since while I think I've ironed most everything out, there probably will be one or two lingering bugs and this might give me a chance to catch one early here before merging to main

**Comment by nikmo33** [comment]
> @nikmo33 If you can lmk if you encounter any weirdness please please lmk, since while I think I've ironed most everything out, there probably will be one or two lingering bugs and this might give me a chance to catch one early here before merging to main

The only issue I have run into so far with cameras.py is on the following line (actually existed prior to this commit as well)
`distortion_params=self.distortion_params[indices + (slice(None),)] if self.distortion_params else None,`
changing it to 
`distortion_params=self.distortion_params[indices + (slice(None),)] if self.distortion_params is not None else None,
`solved the issue. The error before was - 
`RuntimeError: Boolean value of Tensor with more than one value is ambiguous
`

**Comment by jake-austin** [comment]
Can you link to this for me? I'm not sure where this is in the CamerasV2 branch, but I can see why this is an issue and want to make sure this gets patched

**Comment by nikmo33** [comment]
So I created a PR here - https://github.com/nerfstudio-project/nerfstudio/pull/878 I realised that it actually had nothing to do with your branch and was always there! Sorry about the confusion

**Comment by cclaan** [comment]
Hi, I was trying to test an instant-ngp dataset that has cameras with different intrinsic parameters / image resolutions. 
I tried training using this branch but get an error in the loader ( nerfstudio_dataparser.py ). Is this expected? I can dig into it myself but wanted to double check I was not missing something obvious like using a different data loader. 
Thanks

**Comment by jake-austin** [comment]
@cclaan Can you send the error and lmk what commit you're on using git log? I've seen some errors in the CacheDataloader when it tries to collate images of different sizes (I had to do some janky stuff to get around that), but none from the nerfstudio_dataparser.py file

**Comment by cclaan** [comment]
@jake-austin I'm on commit b7adc85ec61ec19c1dbefc8c7983eb82a0d7dc81 (HEAD -> CamerasV2, origin/CamerasV2)

The error is:
```
  File "/opt/conda/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/cc/nerfstudio/scripts/train.py", line 248, in entrypoint
    main(
  File "/home/cc/nerfstudio/scripts/train.py", line 234, in main
    launch(
  File "/home/cc/nerfstudio/scripts/train.py", line 173, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/cc/nerfstudio/scripts/train.py", line 87, in train_loop
    trainer.setup()
  File "/home/cc/nerfstudio/nerfstudio/engine/trainer.py", line 111, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/cc/nerfstudio/nerfstudio/configs/base_config.py", line 63, in setup
    return self._target(self, **kwargs)
  File "/home/cc/nerfstudio/nerfstudio/pipelines/dynamic_batch.py", line 56, in __init__
    super().__init__(config, device, test_mode, world_size, local_rank)
  File "/home/cc/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 213, in __init__
    self.datamanager: VanillaDataManager = config.datamanager.setup(
  File "/home/cc/nerfstudio/nerfstudio/configs/base_config.py", line 63, in setup
    return self._target(self, **kwargs)
  File "/home/cc/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 301, in __init__
    self.train_dataset = self.create_train_dataset()
  File "/home/cc/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 307, in create_train_dataset
    return InputDataset(self.config.dataparser.setup().get_dataparser_outputs(split="train"))
  File "/home/cc/nerfstudio/nerfstudio/data/dataparsers/base_dataparser.py", line 116, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split)
  File "/home/cc/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py", line 156, in _generate_dataparser_outputs
    fx=float(meta["fl_x"]),
KeyError: 'fl_x'
```

Looks like the data parser expects camera params at the top level node in the json file, but they are set for each frame like this:
```
{
    "aabb_scale": 16,
    "frames": [
        {
            "file_path": "./images/0-902.png",
            "sharpness": 716.2955340834449,
            "transform_matrix": [...],
            "camera_angle_x": 0.7282937663575824,
            "camera_angle_y": 1.191054437810502,
            "fl_x": 944.5231934808648,
            "fl_y": 944.5231934808648,
            "k1": 0.03109374921404926,
            "k2": 0,
            "p1": 0,
            "p2": 0,
            "cx": 360.0,
            "cy": 640.0,
            "w": 720.0,
            "h": 1280.0
        },
```

Thanks

**Comment by lkskstlr** [comment]
@jake-austin I am seeing the same error. Could you maybe post a small working example on how to use nerfstudio with multiple different cameras, maybe with a link to a dataset for which it works?

Thank you all for the amazing package and I know that your TODO lists are probably overflowing like crazy. If you don't have time, that's fine :)

**Comment by jake-austin** [comment]
> @jake-austin I am seeing the same error. Could you maybe post a small working example on how to use nerfstudio with multiple different cameras, maybe with a link to a dataset for which it works?
> 
> Thank you all for the amazing package and I know that your TODO lists are probably overflowing like crazy. If you don't have time, that's fine :)

@lkskstlr We have this all working now, it's just in review to make sure the code is clean / high quality with no low hanging fruit in terms of speedups available. If you want to see a working example, go to the NerfW branch, which has the phototourism dataset added, which works just fine. 

Can you provide more details for me on what code you've added to this branch or what scene is giving you this error? I'm using the default nerfstudio dozer, and it seems to work just fine for me.

**Comment by lkskstlr** [comment]
Thank you, will try out the NerfW branch and circle back!

**Comment by cclaan** [comment]
@jake-austin Thanks for the info. My use case is loading an existing Instant NGP dataset which has different cameras. Should I switch to the GeneralizedDataset, or should the instant_ngp_dataparser.py handle different cameras on this new branch?

**Comment by jake-austin** [comment]
@cclaan Yeah you should be using a GeneralizableDataset, since otherwise the CacheDataloader will try and batch images of different sizes together by concatenating them which doesn't work. I'd just switch to the NerfW branch, which is by default using the GeneralizableDataset unless your images are all the same size

**Comment by lkskstlr** [comment]
Thanks :)

So I switched to the NerfW branch and adapted the `phototourism_dataparser.py`. Nice work on the `Cameras(TensorDataclass)`: the batching looks quite intricate to get correct.

Now, I have Prespective and Fisheye cameras mixed and still don't have it working 100%. I commented out the `assert` in the original dataparser and load the `cameras` with `distortion_params` and `camera_types` set to tensors. Wrt. the distortion it looks like fisheye is ignored (https://github.com/nerfstudio-project/nerfstudio/blob/NerfW/nerfstudio/cameras/cameras.py#L587)? While the ray generation looks like it considers different camera types (https://github.com/nerfstudio-project/nerfstudio/blob/NerfW/nerfstudio/cameras/cameras.py#L607). In that case the fisheye cameras have static-like noise which looks like I am missing a bug. I guess that is also the reason why the assert was there?

Are mixtures of perspective and fisheye cameras supported now and the bug is on my end, or are they not supported yet? If not yet: Do you have an idea on when you will support that?

Thanks again for the open source code :) I am very grateful for what's there and can implement things myself if necessary!

**Comment by jake-austin** [comment]
> 

There might be some bugs we haven't yet identified that show up in datasets of both fisheye and perspective. I know either one works alone since the nerfstudio dozer is fisheye and it seems to work just fine and for phototourism we used perspective and those work fine. I think the distortion shouldn't be ignored. The hope was that when you had a mix of fisheye cameras and perspective cameras, you would set distortion on the fisheyes to whatever you need it to be, and then on the perspective cameras (so long as no distortion) you set it to be zeros (i think zeros correspond to no distortion, but I might be mistaken).

I realize there might be a bug in the collate function where if one camera has "None" for the distortion params, we are overwriting the collated cameras to all have "None", but that probably shouldn't effect you once you've made your dataparser which has the batch of cameras already done.

**Comment by jake-austin** [comment]
@lkskstlr Are you by chance setting the camera distortion params to all be None even though you have a mix of cameras? I was trying to figure out what you meant by the distortion params being ignored, and I can see how you could come to that conclusion if you're setting the distortion params to be "None", and if so, that might be what's causing your issue

**Comment by lkskstlr** [comment]
Thanks for the quick reply. No, I set them to values as the perspective cameras currently still have distortion. Following your hint, I could undistort that out though.

One thing is the `elif` here: https://github.com/nerfstudio-project/nerfstudio/blob/NerfW/nerfstudio/cameras/cameras.py#L607. This means the second part would never be triggered on a mixed batch, right?

I'll call it a day for now and debug further tomorrow. Thank you for the quick help! I will at minimum report bugs and if/how I made it work :+1:

**Comment by lkskstlr** [comment]
I wrote ignored because there is only one function call with the distortion parameters: `coord_stack = camera_utils.radial_and_tangential_undistort(coord_stack, distortion_params)`. I initially thought that there should be at least two: One for perspective and one for fisheye. But after looking into it, it seems that both use the same function. This seems overall like a neat solution, but I think the equations only agree for `k4==0`. I think your equation with `k4 != 0` is not what opencv uses?

opencv perspective: https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html
opencv fisheye: https://docs.opencv.org/3.4/db/d58/group__calib3d__fisheye.html

![Screenshot from 2022-11-15 20-40-01](https://user-images.githubusercontent.com/14993470/202085315-6067a47e-695b-43e5-b10a-7acb56e9e8a8.png)
![Screenshot from 2022-11-15 20-39-42](https://user-images.githubusercontent.com/14993470/202085317-4c8964b0-bc1d-442b-ada1-bb3e70ee34ca.png)

**Comment by jake-austin** [comment]
Shoot, I think I edited your last comment @lkskstlr instead of editing the one above it, sorry, trying to figure out how to undo that

**Comment by lkskstlr** [comment]
Doesn't matter, I actually found it quite funny :)

**Comment by jake-austin** [comment]
Fixed lol, really sorry I'm reaaaaaally bad at using github comments

**Comment by jake-austin** [comment]
Any rate, I'm making a PR to fix the bug you found, I feel very silly for having made that bug, thanks for the fix! Lmk if it works after I push this change to the CamerasV2 branch and the NerfW branch

**Comment by lkskstlr** [comment]
I think writing this many lines of code without a bug is impossible. I am really impressed with the speed you guys are committing new features to the repo :rocket:

**Comment by jake-austin** [comment]
@lkskstlr Should be fixed. Lmk if this fixes it and btw if you can lmk what dataset you're working with that has both of these camera types / the code you have for the dataparser, I'd love to be able to use it to test stuff out and verify that this is working.

**Comment by Madaoer** [comment]
Hi, @jake-austin Thanks for your great work! I read code in https://github.com/nerfstudio-project/nerfstudio/blob/NerfW/nerfstudio/data/dataparsers/phototourism_dataparser.py#L144 and confused by auto_orient_and_center_poses function which seems not using in nerf_pl. Could you give some intuitive explaination?

**Comment by Madaoer** [comment]
Thanks for your kind reply!! I cann't wait to learning more about nerfstudio in dicord channelo^^

**Comment by lkskstlr** [comment]
@jake-austin I think the fix works for me, thanks! Initial results look good, but I would like to do some further digging if maybe smaller things go wrong. Sadly, I can't share the dataset with you, sorry!

Another question: Are you planning to rebase NerfW onto main? I would like to try out the point cloud exporter with the multi-cam NeRF. If that is not an immediate plan for you, just let me know and I will do it internally.

**Comment by jake-austin** [comment]
Yeah it should get merged with main at some point here, I just need to fix some things about it and it will get merged in here

**Comment by jake-austin** [comment]
@lkskstlr @Madaoer @cclaan @nikmo33  The changes have been merged into master. When we get the transients working properly we'll document it a little better, but for now, ns-download-data phototourism has the phototourism datasets for download, and ns-train phototourism will train the nerfacto model with some defaults better for the phototourism dataset

**Comment by thekaka** [comment]
> @jake-austin I'm on commit [b7adc85](https://github.com/nerfstudio-project/nerfstudio/commit/b7adc85ec61ec19c1dbefc8c7983eb82a0d7dc81) (HEAD -> CamerasV2, origin/CamerasV2)
> 
> The error is:
> 
> ```
>   File "/opt/conda/envs/nerfstudio/bin/ns-train", line 8, in <module>
>     sys.exit(entrypoint())
>   File "/home/cc/nerfstudio/scripts/train.py", line 248, in entrypoint
>     main(
>   File "/home/cc/nerfstudio/scripts/train.py", line 234, in main
>     launch(
>   File "/home/cc/nerfstudio/scripts/train.py", line 173, in launch
>     main_func(local_rank=0, world_size=world_size, config=config)
>   File "/home/cc/nerfstudio/scripts/train.py", line 87, in train_loop
>     trainer.setup()
>   File "/home/cc/nerfstudio/nerfstudio/engine/trainer.py", line 111, in setup
>     self.pipeline = self.config.pipeline.setup(
>   File "/home/cc/nerfstudio/nerfstudio/configs/base_config.py", line 63, in setup
>     return self._target(self, **kwargs)
>   File "/home/cc/nerfstudio/nerfstudio/pipelines/dynamic_batch.py", line 56, in __init__
>     super().__init__(config, device, test_mode, world_size, local_rank)
>   File "/home/cc/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 213, in __init__
>     self.datamanager: VanillaDataManager = config.datamanager.setup(
>   File "/home/cc/nerfstudio/nerfstudio/configs/base_config.py", line 63, in setup
>     return self._target(self, **kwargs)
>   File "/home/cc/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 301, in __init__
>     self.train_dataset = self.create_train_dataset()
>   File "/home/cc/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 307, in create_train_dataset
>     return InputDataset(self.config.dataparser.setup().get_dataparser_outputs(split="train"))
>   File "/home/cc/nerfstudio/nerfstudio/data/dataparsers/base_dataparser.py", line 116, in get_dataparser_outputs
>     dataparser_outputs = self._generate_dataparser_outputs(split)
>   File "/home/cc/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py", line 156, in _generate_dataparser_outputs
>     fx=float(meta["fl_x"]),
> KeyError: 'fl_x'
> ```
> 
> Looks like the data parser expects camera params at the top level node in the json file, but they are set for each frame like this:
> 
> ```
> {
>     "aabb_scale": 16,
>     "frames": [
>         {
>             "file_path": "./images/0-902.png",
>             "sharpness": 716.2955340834449,
>             "transform_matrix": [...],
>             "camera_angle_x": 0.7282937663575824,
>             "camera_angle_y": 1.191054437810502,
>             "fl_x": 944.5231934808648,
>             "fl_y": 944.5231934808648,
>             "k1": 0.03109374921404926,
>             "k2": 0,
>             "p1": 0,
>             "p2": 0,
>             "cx": 360.0,
>             "cy": 640.0,
>             "w": 720.0,
>             "h": 1280.0
>         },
> ```
> 
> Thanks

I met excatly the same problem. I try to use GeneralizedDataset to solve it, but the **NerfW branch** is not found. 

I also tried to pull the main branch just 10mins ago, but nothing changed.

**Comment by jake-austin** [comment]
@thekaka I can't tell exactly when you pulled but make sure you're on main, if you go the the main github, you will see the latest commit has more current stuff pulled in and CamerasV2 branch has been deleted

**Comment by Madaoer** [comment]
@tancik @jake-austin  I try the main branch and get following error.

**Comment by jake-austin** [comment]
@Madaoer Can you verify that you're using the phototourism method or post what you're using on the command line? I don't know if we made it clear enough, but instead of using "ns-train nerfacto" you need to use "ns-train phototourism" until such a time as we make it easier to hotswap in different datamangers from the command line. I'm betting you're using nerfacto method since the phototourism method's dataloader shouldn't ever try and stack images, but if you are, then can you post the full command and the full stack trace too?

**Comment by Madaoer** [comment]
> @Madaoer Can you verify that you're using the phototourism method or post what you're using on the command line? I don't know if we made it clear enough, but instead of using "ns-train nerfacto" you need to use "ns-train phototourism" until such a time as we make it easier to hotswap in different datamangers from the command line. I'm betting you're using nerfacto method since the phototourism method's dataloader shouldn't ever try and stack images, but if you are, then can you post the full command and the full stack trace too?

@jake-austin Yes,you are right. I use ns-train nerfacto command, thank you !

**Comment by GaoPeng97** [comment]
@jake-austin Thanks for your great job. 
Through all the comments above, could we reach a conclusion that the newest code in main branch has supported cameras with different parameters.  The data format be like this:

> {
>     "aabb_scale": 16,
>     "frames": [
>         {
>             "file_path": "./images/0-902.png",
>             "sharpness": 716.2955340834449,
>             "transform_matrix": [...],
>             "camera_angle_x": 0.7282937663575824,
>             "camera_angle_y": 1.191054437810502,
>             "fl_x": 944.5231934808648,
>             "fl_y": 944.5231934808648,
>             "k1": 0.03109374921404926,
>             "k2": 0,
>             "p1": 0,
>             "p2": 0,
>             "cx": 360.0,
>             "cy": 640.0,
>             "w": 720.0,
>             "h": 1280.0
>         },

 but the data part of documentation has not been updated, I mean this part https://docs.nerf.studio/en/latest/quickstart/data_conventions.html .  Is that correct ?

**Comment by cclaan** [comment]
@GaoPeng97 That looks like an Instant NGP style transforms.json file , I don't think the current codebase supports reading that. I was able to get something working by modifying the existing instant_ngp_dataparser.py ( I've attached my hacked together version here [instant_ngp_mixed_dataparser.py](https://gist.github.com/cclaan/b30f1ae01586eeaf9dc4299242fb9550) ) You also have to create a new config that uses the variable resolution datamanager ( VariableResDataManagerConfig ) and add it to 'method_configs.py'
Here is a sample config where I modified the 'nerfacto' config.

```python
method_configs["nerfacto_mixed"] = ExperimentConfig(
    method_name="nerfacto_mixed",
    trainer=TrainerConfig(
        steps_per_eval_batch=500, steps_per_save=2000, max_num_iterations=30000, mixed_precision=True
    ),
    pipeline=VanillaPipelineConfig(
        datamanager=VariableResDataManagerConfig(
            dataparser=InstantNGPMixedDataParserConfig(),
            train_num_rays_per_batch=4096,
            eval_num_rays_per_batch=4096,
            camera_optimizer=CameraOptimizerConfig(
                mode="SO3xR3", optimizer=AdamOptimizerConfig(lr=6e-4, eps=1e-8, weight_decay=1e-2)
            ),
        ),
        model=NerfactoModelConfig(eval_num_rays_per_chunk=1 << 15),
    ),
    optimizers={
        "proposal_networks": {
            "optimizer": AdamOptimizerConfig(lr=1e-2, eps=1e-15),
            "scheduler": None,
        },
        "fields": {
            "optimizer": AdamOptimizerConfig(lr=1e-2, eps=1e-15),
            "scheduler": None,
        },
    },
    viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
    vis="viewer",
)
```


I was doing this quickly to get something working, so there is no error handling etc.
You may also be able set the dataparser / datamanager from command line args too.

**Comment by tancik** [comment]
> @jake-austin Thanks for your great job. Through all the comments above, could we reach a conclusion that the newest code in main branch has supported cameras with different parameters. The data format be like this:
> 
> > {
> > "aabb_scale": 16,
> > "frames": [
> > {
> > "file_path": "./images/0-902.png",
> > "sharpness": 716.2955340834449,
> > "transform_matrix": [...],
> > "camera_angle_x": 0.7282937663575824,
> > "camera_angle_y": 1.191054437810502,
> > "fl_x": 944.5231934808648,
> > "fl_y": 944.5231934808648,
> > "k1": 0.03109374921404926,
> > "k2": 0,
> > "p1": 0,
> > "p2": 0,
> > "cx": 360.0,
> > "cy": 640.0,
> > "w": 720.0,
> > "h": 1280.0
> > },
> 
> but the data part of documentation has not been updated, I mean this part https://docs.nerf.studio/en/latest/quickstart/data_conventions.html . Is that correct ?

You are correct. We still need to update the docs.

**Comment by GaoPeng97** [comment]
@cclaan  Thanks for your really detailed response. That helps me a lot.  I implement what you mentioned in the response. Although experiment running normally, something strange happens when I visualize the input data. Taking your "poster" dataset as an example, it seems that the images are rotated 90 degree. Like what shown in the below:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/22500679/209676393-ca89545b-7d0a-4012-9565-3ba8fca2d951.png">

I just transfer original transforms.json to fit the data format of a mixed camera version.
<img width="994" alt="image" src="https://user-images.githubusercontent.com/22500679/209676917-37e3b6c7-a129-4a20-8f36-b45263c4fc93.png">
 
I failed to figure out what causing this :(     
I have not been familiar with this repo enough. 

May I ask if you have some suggestions on that ?

**Comment by cclaan** [comment]
@GaoPeng97 Hm, I'm not sure why that would happen sorry ( I'm also not very familiar with the codebase. )

**Comment by tancik** [comment]
@GaoPeng97 what command are you using to train? The default `nerfstudio-data` dataparser should auto-orient and scale the scene.

**Comment by KamiCalcium** [comment]
> I wrote ignored because there is only one function call with the distortion parameters: `coord_stack = camera_utils.radial_and_tangential_undistort(coord_stack, distortion_params)`. I initially thought that there should be at least two: One for perspective and one for fisheye. But after looking into it, it seems that both use the same function. This seems overall like a neat solution, but I think the equations only agree for `k4==0`. I think your equation with `k4 != 0` is not what opencv uses?
> 
> opencv perspective: https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html opencv fisheye: https://docs.opencv.org/3.4/db/d58/group__calib3d__fisheye.html
> 
> ![Screenshot from 2022-11-15 20-40-01](https://user-images.githubusercontent.com/14993470/202085315-6067a47e-695b-43e5-b10a-7acb56e9e8a8.png) ![Screenshot from 2022-11-15 20-39-42](https://user-images.githubusercontent.com/14993470/202085317-4c8964b0-bc1d-442b-ada1-bb3e70ee34ca.png)

Do we have a conclusion towards this in the current implementation?

**Comment by jake-austin** [comment]
> > I wrote ignored because there is only one function call with the distortion parameters: `coord_stack = camera_utils.radial_and_tangential_undistort(coord_stack, distortion_params)`. I initially thought that there should be at least two: One for perspective and one for fisheye. But after looking into it, it seems that both use the same function. This seems overall like a neat solution, but I think the equations only agree for `k4==0`. I think your equation with `k4 != 0` is not what opencv uses?
> > opencv perspective: https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html opencv fisheye: https://docs.opencv.org/3.4/db/d58/group__calib3d__fisheye.html
> > ![Screenshot from 2022-11-15 20-40-01](https://user-images.githubusercontent.com/14993470/202085315-6067a47e-695b-43e5-b10a-7acb56e9e8a8.png) ![Screenshot from 2022-11-15 20-39-42](https://user-images.githubusercontent.com/14993470/202085317-4c8964b0-bc1d-442b-ada1-bb3e70ee34ca.png)
> 
> @jake-austin Do we have a conclusion towards this in the current implementation? Seems like it is still 'ignoring' the fisheye distortion (not considering theta = atan(r) at all) in
> 
> https://github.com/nerfstudio-project/nerfstudio/blob/408ab709ec62c2d4981aa218e7a53ed534761919/nerfstudio/cameras/camera_utils.py#L323-L338

I'm not 100% sure since a fair bit of this code is copied over from the old cameras only with the new code to support variable resolution cameras being batched, but my understanding was the camera_utils.radial_and_tangential_undistort function took care of all that. If you think it's an issue, I might make a separate issue since at this point this thread serves more as a reminder to me to update the documentation and make comprehensive documentation for our data types in general.
