### ISSUE TITLE
Unable to exit the training normally

### ISSUE THREAD

**Issue by jhzgjhzg** [nerfstudio-project/nerfstudio#908]
After 99.97% of the model training, it was stuck and could not be completed normally.
The command executed is: 
`ns-train nerfacto --vis viewer --viewer.websocket-port=7007 nerfstudio-data --data /home/nhy123456/nerfstudio/test_data`
This is the error message after I exit with ctrl+c:<img width="869" alt="image" src="https://user-images.githubusercontent.com/101122762/200169071-60ddbbcb-eab3-4a66-98bb-96fbd8831a45.png">

**Comment by tancik** [comment]
The model completed training correctly, we have an off-by-one logging error which is why you don't see the last log. The codes does not automatically quit as this would close the viewer (which may not be desirable). We can certainly make the UI around completion better, perhaps add "training is complete, press q to quit" at the end.
